name = "wasmlab"
gas_price = '0.025ujunox'
account_prefix = 'juno'

[networks.local]
chain_id = 'testing'
network_variant = 'Local'
grpc_endpoint = 'http://localhost:9090'
rpc_endpoint = 'http://localhost:26657'

[accounts.test1]
mnemonic = 'siren window salt bullet cream letter huge satoshi fade shiver permit offer happy immense wage fitness goose usual aim hammer clap about super trend'